version: '3.8'

services:
  api-gateway:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./html:/usr/share/nginx/html/pages:ro
      - ./styles:/usr/share/nginx/html/styles:ro
    networks:
      - pokestop-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  authentication-service:
    image: pokestop/authentication-service:latest
    environment:
      - PORT=3000
      - NODE_ENV=production
      - JWT_SECRET=${JWT_SECRET:-pokestop-secret-change-in-production}
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=enter
      - DB_NAME=pokestop_auth_db
    networks:
      - pokestop-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  user-service:
    image: pokestop/user-service:latest
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - NODE_ENV=production
      - JWT_SECRET=${JWT_SECRET:-pokestop-secret-change-in-production}
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=enter
      - DB_NAME=pokestop_users_db
    networks:
      - pokestop-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  team-service:
    image: pokestop/team-service:latest
    environment:
      - PORT=3002
      - NODE_ENV=production
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=enter
      - DB_NAME=pokestop_teams_db
    networks:
      - pokestop-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  pokedex-service:
    image: pokestop/pokedex-service:latest
    environment:
      - PORT=3003
      - NODE_ENV=production
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=enter
      - DB_NAME=pokestop_pokedex_db
    networks:
      - pokestop-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  collection-service:
    image: pokestop/collection-service:latest
    environment:
      - PORT=3004
      - MONGO_URI=mongodb://root:enter@mongodb:27017/pokestop_collection_db?authSource=admin
      - DB_NAME=pokestop_collection_db
      - POKEDEX_SERVICE_URL=http://pokedex-service:3003
      - JWT_SECRET=${JWT_SECRET:-pokestop-secret-change-in-production}
    networks:
      - pokestop-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  encounter-service:
    image: pokestop/encounter-service:latest
    environment:
      - PORT=3005
      - NODE_ENV=production
      - JWT_SECRET=${JWT_SECRET:-pokestop-secret-change-in-production}
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=enter
      - DB_NAME=pokestop_encounter_db
      - POKEDEX_SERVICE_URL=http://pokedex-service:3003
      - COLLECTION_SERVICE_URL=http://collection-service:3004
    networks:
      - pokestop-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  db:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD:-enter}
      - MYSQL_ROOT_HOST=%
    volumes:
      - mysql-data:/var/lib/mysql
      - ./database-schemas/init-mysql.sql:/docker-entrypoint-initdb.d/init-mysql.sql:ro
    networks:
      - pokestop-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    command: --default-authentication-plugin=mysql_native_password

  mongodb:
    image: mongo:7.0
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=pokestop_collection_db
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD:-enter}
    volumes:
      - mongodb-data:/data/db
      - ./database-schemas/init-mongodb.js:/docker-entrypoint-initdb.d/init-mongodb.js:ro
    networks:
      - pokestop-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  pokestop-network:
    driver: overlay

volumes:
  mysql-data:
  mongodb-data:
